### ISSUE TITLE
Is it possible to get the max execution time for each line?

### ISSUE THREAD

**Issue by yahiaali** [pyutils/line_profiler#107]
Looking at the example in the README, the "per hit" time appears to be an average time it takes for each line to execute:
```
Pystone(1.1) time for 50000 passes = 2.48
This machine benchmarks at 20161.3 pystones/second
Wrote profile results to pystone.py.lprof
Timer unit: 1e-06 s

File: pystone.py
Function: Proc2 at line 149
Total time: 0.606656 s

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   149                                           @profile
   150                                           def Proc2(IntParIO):
   151     50000        82003      1.6     13.5      IntLoc = IntParIO + 10
   152     50000        63162      1.3     10.4      while 1:
   153     50000        69065      1.4     11.4          if Char1Glob == 'A':
   154     50000        66354      1.3     10.9              IntLoc = IntLoc - 1
   155     50000        67263      1.3     11.1              IntParIO = IntLoc - IntGlob
   156     50000        65494      1.3     10.8              EnumLoc = Ident1
   157     50000        68001      1.4     11.2          if EnumLoc == Ident1:
   158     50000        63739      1.3     10.5              break
   159     50000        61575      1.2     10.1      return IntParIO
```
I am interested in understanding the distribution of execution times for each line. For example, one line may execute in under 10 microseconds on average, but it may have a peak execution time of 1000 microseconds (i.e. some iterations are slower than others). **To detect such cases, is it possible to compute the maximum execution time of each line?**

**Comment by Erotemic** [comment]
If you wanted that you would need to modify the cython code to store that information. https://github.com/pyutils/line_profiler/blob/main/line_profiler/_line_profiler.pyx#L56 

Currently it only stores the total time and the number of hits, so it is not possible to get the maximum time with the existing code.

There is also a trade-off here. Because we are trying to profile the code (and not the profiler) it is important that the profiler itself be as lightweight as possible. I'm not sure how big of an impact it would be to keep track of extra information like this.
