### ISSUE TITLE
kernprof fails to write to stdout if stdout was replaced

### ISSUE THREAD

**Issue by impact27** [pyutils/line_profiler#109]
To reproduce:
save to `test.py`:
```python
import time
import sys
import io
@profile
def fun():
    time.sleep(1)

sys.stdout = io.StringIO()
print("Writing to a sting!")
fun()
```
Run `kernprof -lv test.py`

Nothing is shown.

**Comment by Erotemic** [comment]
Hmm, I'm unsure if this should be classified as a bug or not. I'm inclined towards this being intended behavior, but I'm open to hearing other opinions.

It seems to me that if the user shoots themselves in the foot, it's not line-profiler's responsibility to mitigate that. I could also see cases where restoring sys.stdout might not be the right thing to do. (Imagine the case where you are testing kernprof and you really do want to capture that stdout).

**Comment by impact27** [comment]
Well in that case you can redirect the stdout before invocating kernprof and you would capture it as expected. My proposition in #110 is to restore the stdout state from the beginning of the kernprof script, not put it back to `sys.__stdout__`. The reason I needed this was that I was profiling Spyder. In spyder the stdout is captured to be printed to the internal console. I am not sure that counts as "shooting myself in the foot". 

I guess my argument is: The script is self contained. If you want to capture the stdout from kernprof, you would call kernprof from a script that captures the stdout, rather than profiling a script that captures stdout.

**Comment by Erotemic** [comment]
To make sure I understand the issues. You are starting Spyder with the kernprof script, Spyder captures stdout but never resets it. Thus when kernprof enters the finally block of the main function it writes to the spyder console, which has presumably already been closed because the program is exiting.

I'm wondering if a better way of addressing this is some sort of atexit hook. I don't think the atexit module itself can be used here because kernprof is still running. I also don't like the idea of the user being forced to implement hooks to make their profiling work.

The main issue that I have with the patch is that it makes a presumption that the user wants (or is at least ok with) stdout to be reinstated (although I recognize that most of the time it's moot because the Python interpreter is about to exit anyway). But I'd at least like to think about alternate ways this issue could be approached before accepting the patch.

One idea is that the `prof.print_stats` accepts a `stream` which could be set to the original sys.stdout, and that would avoid the issue of implicitly undoing a change to the globals that the user might not have expected. But that has the problem that the print_stats method for a ContextualProfile doesn't seem to have that argument. Although looking at the underlying implementation of that function: https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/pstats.py#L414 it looks like there is some stream object that could be set to the appropriate stream. I think doing something like that is a slightly more explicit and non-intrusiveness patch that would also fix the issue.

**Comment by impact27** [comment]
That is correct.

My opinion is that if I profile a script, I don't expect the script to be able to interfere with the profiling. I would expect the profiler to be an external observer that would do something like creating a new python interpreter and running the script in it, collecting data. When the script is done it would collect the data and do something with it. I think the assumption that the script you run modifies the profiler is more surprising than the other way. The script shouldn't affect the profiler except for the time it takes to execute.

If you think an option to enable/disable the stdout reinstitution is necessary, I think the least surprising default is to have it on.

Having said that it would probably make sense to patch spyder to restore stdout before closing.
