### ISSUE TITLE
Bypass lru_cache

### ISSUE THREAD

**Issue by flying-sheep** [pyutils/line_profiler#40]
Trying to profile a method wrapped by a @lru_cache, I got `_lru_cache_wrapper object has not attribute __code__`.

This can be easily fixed for functions as well as bound methods, but idk where to best introduce this code in this module.

```py
from types import MethodType

if hasattr(f, '__wrapped__') and callable(getattr(f, 'cache_info', None)):  # Handle lru_cache
    logger.warn(f'Trying to wrap lru_cache’d method {f.__name__}. Bypassing cache')
    f = MethodType(f.__wrapped__, f.__self__) if isinstance(f, MethodType) else f.__wrapped__
```

The reasons this code works are pretty confusing:

```py
class Test:
    def test(self): pass
# Test.test is a *function*, i.e. isinstance(Test.test, FunctionType), even if most people would call it “method”
# Test().test is a *bound method*, i.e. isinstance(Test().test, MethodType)


class Test2:
    @lru_cache
    def test(self): pass
# Test2.test is a functools._lru_cache_wrapper
# Test2().test is a *bound method* that happens to have `cache_clear`, `cache_info` and `__wrapped__` attributes.
```

**Comment by Erotemic** [comment]
Wouldn't it be easier to simply do 

```
class Test2:
    @lru_cache
    @profile
    def test(self): 
        pass
```

and put the profile decorator underneath any lru cache? 

I don't think it would be desirable to make profile ignore decorators, especially if it only does it in a special case.

**Comment by flying-sheep** [comment]
Note that this only circumvents one specific decorator, which in turn is only used to make a function/method *not* execute, and only if you directly want to profile that function/method. Any code leveraging a `lru_cache` will be profiled normally.

I’d expect this is what people want…

And I prefer not to modify production code for temporary profiling, instead I do:

```py
from my_module import MyClass, my_func

thing = MyClass(...)

for f, a in [
    (thing.method_a, (arg1, arg2)),
    (thing.method_b, (arg1, arg3)),
    (my_func, ()),
]:
    profiler = LineProfiler()
    if hasattr(f, '__wrapped__') and hasattr(f, 'cache_info'):  # Handle lru_cache
        f = MethodType(f.__wrapped__, f.__self__) if isinstance(f, MethodType) else f.__wrapped__
    fn = profiler(f)
    rv = fn(*a)
    profiler.print_stats(output_unit=1)
    for o in [str(v) for v in rv] if isinstance(rv, tuple) else [str(rv)]:
        print(o[:131] + '…' if len(o) > 132 else o)
    print()
```

much more flexible than the CLI.

**Comment by Erotemic** [comment]
Right, it seems like a special case behavior that may cause confusion. 

Unfortunately, modifying the code is part of how line_profiler and kernprof are designed to be used. I think modifications to remove this requirement may best be suited for another library.

I'm only a volunteer maintainer of this library, and not the original author. AFAIK there isn't a way to profile functions without explicitly wrapping them in a profile decorator in the existing code right?

**Comment by flying-sheep** [comment]
No, but wrapping them like I do is very straightforwards A version without bells and whistles would be:

```py
for f, a in [
    (thing.method_a, (arg1, arg2)),
    (thing.method_b, (arg1, arg3)),
    (my_func, ()),
]:
    profiler = LineProfiler()
    rv = profiler(f)(*a)
    profiler.print_stats(output_unit=1)
```
```

**Comment by Erotemic** [comment]
I agree, its a nice way to do it. I also have some line profiler wrappers in my xdev package: https://github.com/Erotemic/xdev/blob/master/xdev/profiler.py  

This allows me to simply `import xdev` and wrap functions with `@xdev.profile`. If I specify `--profile` on the command line, it turns on the decorators. Otherwise they are no-ops. This allows me to put them into production without having side effects. I also use the `xdev.profile_now` function a lot in interactive IPython code.

If you have an alternate style of using line profiler. I recommend building a package that extends it with the functionality you're interested in. But I don't think this library is the place for special case conditions. I'm going to close this issue, but feel free to continue the discussion of you want help with designing a new package that extends line_profiler functionality.
