### ISSUE TITLE
Modern viewing tools?

### ISSUE THREAD

**Issue by tony** [pyutils/line_profiler#55]
Where does the community stand with viewing tools for the output of `line_profiler`?

Here's the issue, a lot of these tools are abandoned or won't build across platforms.  The sole exception I found is [snakeviz](https://github.com/jiffyclub/snakeviz/)

Limited to certain platforms
- https://github.com/pwaller/pyprof2calltree/ (via kcachegrind)
- https://github.com/ceefour/wincachegrind

Links of stalled visualization projects:
- http://www.vrplumber.com/programming/runsnakerun/
- https://github.com/venthur/snakerunner (limited to mac)

**Comment by Nodd** [comment]
A few yeas ago I added a viewing tool for line-profiler as a spyder plugin : https://github.com/spyder-ide/spyder-line-profiler. It was inspired by the Matlab profiler, with a stronger color for lines with higher percent time (see screenshot)
I don't know if it still works, but it should be quite easy to use it as a standalone program if anyone is interested.

**Comment by tony** [comment]
@Nodd maybe it'd be a good idea to have a viewer util be maintained by an org (is that what @pyutils is intended for?) or @jazzband.

**Comment by Erotemic** [comment]
@pyutils is an org I created for maintaining line_profiler after rkern wanted to step back from maintenance duties.

If someone wanted to port spyder-line-profiler to a standalone program, I would be willing to take a look and add it to pyutils as long as the author was committed to maintaining it. I think the first step is making the proof-of-concept.

**Comment by jus-x** [comment]
Hi there! 

I thought I'd respond to this issue to bring a line-profiler plugin I made for PyCharm to your attention. 
It uses line_profiler to profile code and visualize the results into the editor directly.

You can find it at https://plugins.jetbrains.com/plugin/16536-line-profiler
It is still pending JetBrains approval but you can already see some screenshots I took from the IDE. I finished developing the first version yesterday (coincidentally not much time after this issue was created).

The plugin is maintained on gitlab: https://gitlab.com/line-profiler-pycharm

I started developing the plugin because I couldn't really find any useful tools to visualize line_profiler output. Maybe this plugin is something that is useful to you guys as well:)

**Comment by Nodd** [comment]
FYI, I started working on a standalone Qt interface : https://github.com/Nodd/lineprofilergui. Comments and reviews are welcome !

@Erotemic I'm not sure yet about long-term maintenance, but at least here is a proof-of-concept.

**Comment by Erotemic** [comment]
I opened a PR to add some docs about what the modern tooling is. Just a stub for now. I'll keep my eye on this thread for more discussion.

**Comment by Nodd** [comment]
FYI I just released v0.2 of https://github.com/Nodd/lineprofilergui
