### ISSUE TITLE
Non-scikit-build build is broken

### ISSUE THREAD

**Issue by mgorny** [pyutils/line_profiler#61]
Not sure why support for non-scikit-build build is kept but it apparently doesn't work anymore:

```
$ python setup.py build
running build
running build_py
file line_profiler.py (for module line_profiler) not found
file line_profiler.py (for module line_profiler) not found
running build_ext
cythoning _line_profiler.pyx to _line_profiler.c
error: /tmp/line_profiler/_line_profiler.pyx
```

**Comment by mgorny** [comment]
(that's after changing `USE_SKBUILD` to `False`)

**Comment by Erotemic** [comment]
I have a nasty habit of leaving dead code around for way too long. It sounds like we should just remove that block? Or is there a reason to still think about supporting non-scikit-build options?

**Comment by mgorny** [comment]
Well, I don't know if there's any intended difference between the two, so I can't tell. That said, I hate scikit-build implicitly calling CMake. I somewhat suspect that non-verbose mode is hiding incorrect build flags and other common stuff but I don't have the time to deal with that right now.

**Comment by Erotemic** [comment]
The main difference is that CMake [is better suited](https://scikit-build.readthedocs.io/en/latest/usage.html) to handle cross platform building than the distutils c-extension modules in addition to handling dependencies (which isn't an issue for this project, but in general it is). CMake can also be executed outside of the context of scikit-build, which I find helpful for debugging.

Note that using scikit-build is exactly as explicit in its build logic as distutils is. But instead of the manifest of sources being listed in your setup.py it is in the CMakeLists.txt, which is extremely standard for compiled software.

Not that scikit-build can't improve, it can, especially with respect to transparency of error messages when being invoked through setup.py. Using `--verbose` helps, but only so much.

**Comment by Erotemic** [comment]
The new version should use pure-cython by default.
