### ISSUE TITLE
Emoji in a commit message breaks gitk

### ISSUE THREAD

**Issue by Erotemic** [pyutils/line_profiler#71]
The commit "74cba21ee7242cd8d37bca9e310a8f9e40f8da05" by @s-weigand contained an emoji, which caused gitk to crash on me. See issue: https://github.com/googlefonts/noto-emoji/issues/327

In the future we should avoid using emojiis in commit messages while this is still a problem. I'm not sure if there is a good way to clean up that commit message given that there have been releases that build on top of it.

**Comment by s-weigand** [comment]
Sorry for that 😥 

Since changing the commit message would rewrite the history from that point on, I also don't see a clean way to change it without rewriting the history.

Also, I just tried it on Windows from git-bash, and even so the emojis don't render properly (most likely due to an incompatible font) it didn't crash. So this might be more a font/OS/renderer issue than gitk.
